	           E'\n  (u): ' || pg_catalog.pg_get_expr(polqual, polrelid)
	       ELSE E''
	       END
	    || CASE WHEN polwithcheck IS NOT NULL THEN
	           E'\n  (b): ' || pg_catalog.pg_get_expr(polwithcheck, polrelid)
	       ELSE E''
	       END    || CASE WHEN polroles <> '{0}' THEN
	           E'\n  to: ' || pg_catalog.array_to_string(
	               ARRAY(
	                   SELECT rolname
	                   FROM pg_catalog.pg_roles
	                   WHERE oid = ANY (polroles)
	                   ORDER BY 1
	               ), E', ')
	       ELSE E''
	       END
	    FROM pg_catalog.pg_policy pol
	    WHERE polrelid = b.oid), E'\n')
	    AS "Policies"
	FROM pg_catalog.pg_class b
	     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = b.relnamespace
	WHERE b.relkind IN ('r','v','m','S','f','p')
	  AND b.relname OPERATOR(pg_catalog.~) '^(grandchild)$' COLLATE pg_catalog.default
	  AND n.nspname !~ '^pg_' AND pg_catalog.pg_table_is_visible(b.oid)
	ORDER BY 1, 2;
2022-08-02 01:07:47.108 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.108 UTC [42061] STATEMENT:  
	
	-- column reordering
	COPY id (idx, idx) TO stdout;
2022-08-02 01:07:47.108 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.108 UTC [42061] STATEMENT:  
	
	SET SESSION AUTHORIZATION regress_rls_copy_user;
2022-08-02 01:07:47.108 UTC [42061] ERROR:  could not find pg_class tuple for index 2662 at character 45
2022-08-02 01:07:47.108 UTC [42061] STATEMENT:  SELECT b.oid,
	  n.nspname,
	  b.relname
	FROM pg_catalog.pg_class b
	     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = b.relnamespace
	WHERE b.relname OPERATOR(pg_catalog.~) '^(grandchild)$' COLLATE pg_catalog.default
	  AND pg_catalog.pg_table_is_visible(b.oid)
	ORDER BY 2, 3;
2022-08-02 01:07:47.108 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.108 UTC [42061] STATEMENT:  
	
	-- Cleanup: pxtest3 no longer needed.
	DROP TABLE pxtest3;
2022-08-02 01:07:47.108 UTC [42061] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-02 01:07:47.108 UTC [42061] STATEMENT:  
	CREATE TABLE hash_split_heap  PARTITION OF j for VALUES in ('hash_split_index', 'keycol');
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  
	DROP ROLE regress_rls_copy_user_colperms;
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  CREATE TYPE deptest_enum AS ENUM ('red');
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  CREATE TABLE deptest2 (f1 int);
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  CREATE SEQUENCE ss1;
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  COMMENT ON CONSTRAINT the_constraint ON DOMAIN no_comments_dom IS 'another bad comment';
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  SELECT 'a & g' <-> 'b | d'::tsquery;
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  SELECT 'a b:89  ca:23A,64b d:34c'::tsvector @@ 'd:AC & ca:CB' as "true";
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  SELECT 'wa:1D wb:2A'::tsvector @@ 'w:*D & w:*A'::tsquery as "true";
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  SELECT 'wa:1A'::tsvector @@ 'w:*A'::tsquery as "true";
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  select to_tsvector('simple', 'q x') @@ 'q <-> (x | y <-> z)' AS "true";
2022-08-02 01:07:47.109 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.109 UTC [42061] STATEMENT:  SELECT ts_rank(' a:1 s:2 d g'::tsvector, 'a | s');
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  SELECT ts_rank_cd(' a:1 s:2C d g'::tsvector, 'a | s');
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  SELECT ts_rank_cd(' a:1 s:2 d g'::tsvector, 'a & s');
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  SELECT ts_rank_cd(' a:1 s:2A d g'::tsvector, 'a <-> s');
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  SELECT ts_rank_cd(' a:1 sa:2A sb:2D g'::tsvector, 'a <-> s:* <-> sa:A');
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  SELECT ts_delete('base:7 hidden:6 rebel:1 spaceship:2,33A,34B,35C,36D strike:3'::tsvector, 'spaceship');
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  SELECT array_to_tsvector(ARRAY['base','hidden','rebel','spaceship','strike']);
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  SELECT setweight('a:1,3A asd:1C w:5,6,12B,13A zxc:81,222A,567'::tsvector, 'c');
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-02 01:07:47.110 UTC [42061] WARNING:  there is no transaction in progress
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  DISCARD ALL;
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-02 01:07:47.110 UTC [42061] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:07:47.110 UTC [42061] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-02 01:07:49.217 UTC [44636] PANIC:  could not open critical system index 2662
2022-08-02 01:07:49.220 UTC [39781] LOG:  server process (PID 44636) was terminated by signal 6: Aborted
2022-08-02 01:07:49.220 UTC [39781] LOG:  terminating any other active server processes
2022-08-02 01:07:49.250 UTC [39781] LOG:  all server processes terminated; reinitializing
2022-08-02 01:07:49.328 UTC [44639] LOG:  database system was interrupted; last known up at 2022-08-02 01:07:36 UTC
2022-08-02 01:07:49.340 UTC [44639] LOG:  recovered replication state of node 1 to 0/0
2022-08-02 01:07:49.340 UTC [44639] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-02 01:07:49.341 UTC [44639] LOG:  redo starts at 0/3D3AFE0
2022-08-02 01:07:49.341 UTC [44639] LOG:  invalid record length at 0/3D3B408: wanted 24, got 0
2022-08-02 01:07:49.341 UTC [44639] LOG:  redo done at 0/3D3B3E0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-08-02 01:07:49.355 UTC [39781] LOG:  database system is ready to accept connections
2022-08-02 01:07:49.372 UTC [44648] LOG:  logical replication apply worker for subscription "regress_testsub" has started
2022-08-02 01:07:49.372 UTC [44648] ERROR:  could not connect to the publisher: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
		Is the server running locally and accepting connections on that socket?
2022-08-02 01:07:49.378 UTC [39781] LOG:  background worker "logical replication worker" (PID 44648) exited with exit code 1
2022-08-02 01:07:50.062 UTC [44708] LOG:  connection received: host=127.0.0.1 port=60284
2022-08-02 01:07:50.064 UTC [44708] LOG:  connection authorized: user=postgres database=x
2022-08-02 01:07:50.064 UTC [44708] PANIC:  could not open critical system index 2662
2022-08-02 01:07:50.066 UTC [39781] LOG:  server process (PID 44708) was terminated by signal 6: Aborted
2022-08-02 01:07:50.067 UTC [39781] LOG:  terminating any other active server processes
2022-08-02 01:07:50.071 UTC [44714] LOG:  connection received: host=127.0.0.1 port=60288
2022-08-02 01:07:50.071 UTC [44714] FATAL:  the database system is in recovery mode
2022-08-02 01:07:50.074 UTC [39781] LOG:  all server processes terminated; reinitializing
2022-08-02 01:07:50.082 UTC [39781] LOG:  received smart shutdown request
2022-08-02 01:07:50.083 UTC [44720] LOG:  database system was interrupted; last known up at 2022-08-02 01:07:49 UTC
2022-08-02 01:07:50.099 UTC [44720] LOG:  recovered replication state of node 1 to 0/0
2022-08-02 01:07:50.099 UTC [44720] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-02 01:07:50.099 UTC [44720] LOG:  invalid record length at 0/3D3B480: wanted 24, got 0
2022-08-02 01:07:50.099 UTC [44720] LOG:  redo is not required
