2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  SELECT oid as "ID",
	  pg_catalog.pg_get_userbyid(lomowner) as "Owner",
	  pg_catalog.array_to_string(lomacl, E'\n') AS "Access privileges",
	  pg_catalog.obj_description(oid, 'pg_largeobject') as "Description"
	FROM pg_catalog.pg_largeobject_metadata
	ORDER BY oid
	;
2022-08-02 01:31:56.830 UTC [72730] ERROR:  could not find pg_class tuple for index 2662 at character 146
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  SELECT oid as "ID",
	  pg_catalog.pg_get_userbyid(lomowner) as "Owner",
	  pg_catalog.obj_description(oid, 'pg_largeobject') as "Description"
	FROM pg_catalog.pg_largeobject_metadata
	ORDER BY oid
	;
2022-08-02 01:31:56.830 UTC [72730] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  CREATE TABLE b (foo oid, test1_a_idx integer);
2022-08-02 01:31:56.830 UTC [72730] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  SELECT schema_to_xmlschema('testxmlschema', false, true, '');
2022-08-02 01:31:56.830 UTC [72730] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  BEGIN;
2022-08-02 01:31:56.830 UTC [72730] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  SELECT schema_to_xmlschema('testxmlschema', true, false, '');
2022-08-02 01:31:56.830 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user8;
2022-08-02 01:31:56.830 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user9;
2022-08-02 01:31:56.830 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  CREATE FUNCTION test1(integer,integer) RETURNS boolean
	  AS 'int4lt'
	  LANGUAGE internal IMMUTABLE STRICT;
2022-08-02 01:31:56.830 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  REVOKE ALL ON atest1 FROM PUBLIC;
2022-08-02 01:31:56.830 UTC [72730] ERROR:  LOCK TABLE can only be used in transaction blocks
2022-08-02 01:31:56.830 UTC [72730] STATEMENT:  LOCK atest2 IN ACCESS EXCLUSIVE MODE;
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user6;
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662 at character 13
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  DELETE FROM pg_catalog.pg_class;
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  SELECT session_user, current_user;
2022-08-02 01:31:56.831 UTC [72730] WARNING:  there is no transaction in progress
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user4;
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  CREATE INDEX ON atest12 (a);
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662 at character 44
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  SELECT lo_lseek(test1_a_idx, 2030, 0) FROM b;
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  DROP FUNCTION leak2(integer, integer) CASCADE;
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  CREATE TABLE atest3 (one int, two int, three int);
2022-08-02 01:31:56.831 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.831 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user1;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  GRANT SELECT (one), INSERT (two), UPDATE (three) ON atest5 TO regress_priv_user4;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  GRANT SELECT (one,two) ON atest6 TO regress_priv_user4;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user4;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  SELECT lo_get(32715, 10, 20);
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662 at character 25
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  SELECT lo_put(32715, 5, decode('afafafaf', 'hex'));
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user4;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user1;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  GRANT SELECT (one,two,blue) ON atest6 TO regress_priv_user4;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user1;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  GRANT SELECT (c1) ON t1 TO regress_priv_user2;
2022-08-02 01:31:56.832 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.832 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user2;
2022-08-02 01:31:56.832 UTC [72730] WARNING:  there is no transaction in progress
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  REVOKE SELECT (one,blue) ON atest6 FROM regress_priv_user4;
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user3;
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  SET SESSION AUTHORIZATION regress_priv_user1;
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  TRUNCATE atestp1;
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  TRUNCATE atestc;
2022-08-02 01:31:56.833 UTC [72730] WARNING:  there is no transaction in progress
2022-08-02 01:31:56.833 UTC [72730] WARNING:  there is no transaction in progress
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-02 01:31:56.833 UTC [72730] WARNING:  there is no transaction in progress
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  DISCARD ALL;
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-02 01:31:56.833 UTC [72730] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 01:31:56.833 UTC [72730] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-02 01:31:57.028 UTC [74648] PANIC:  could not open critical system index 2662
2022-08-02 01:31:57.030 UTC [72509] LOG:  server process (PID 74648) was terminated by signal 6: Aborted
2022-08-02 01:31:57.030 UTC [72509] LOG:  terminating any other active server processes
2022-08-02 01:31:57.060 UTC [72509] LOG:  all server processes terminated; reinitializing
2022-08-02 01:31:57.072 UTC [74653] LOG:  database system was interrupted; last known up at 2022-08-02 01:31:36 UTC
2022-08-02 01:31:57.083 UTC [74653] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-02 01:31:57.084 UTC [74653] LOG:  redo starts at 0/167D7A8
2022-08-02 01:31:57.102 UTC [74653] LOG:  invalid record length at 0/176C340: wanted 24, got 0
2022-08-02 01:31:57.102 UTC [74653] LOG:  redo done at 0/176C308 system usage: CPU: user: 0.01 s, system: 0.00 s, elapsed: 0.01 s
2022-08-02 01:31:57.114 UTC [72509] LOG:  database system is ready to accept connections
2022-08-02 01:31:57.979 UTC [74689] WARNING:  there is no transaction in progress
2022-08-02 01:31:57.984 UTC [74689] ERROR:  role "regress_lo_user" already exists
