2022-08-02 08:25:08.732 UTC [79004] STATEMENT:  select avg(null::numeric) from generate_series(1,3);
2022-08-02 08:25:08.732 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 33
2022-08-02 08:25:08.732 UTC [79004] STATEMENT:  select sum('NaN'::numeric) from generate_series(1,3);
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 33
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  select avg('NaN'::numeric) from generate_series(1,3);
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  SELECT sum(x::float8), avg(x::float8), var_pop(x::float8)
	FROM (VALUES ('infinity'), ('1')) v(x);
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  SELECT sum(x::numeric), avg(x::numeric), var_pop(x::numeric)
	FROM (VALUES ('-infinity'), ('infinity')) v(x);
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 15
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  SELECT sum(x::numeric), avg(x::numeric), var_pop(x::numeric)
	FROM (VALUES ('-infinity'), ('-infinity')) v(x);
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  SELECT avg(x::float8), var_pop(x::float8)
	FROM (VALUES (7000000000005), (7000000000007)) v(x);
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  SELECT covar_pop(1::float8,2::float8), covar_samp(3::float8,4::float8);
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  CREATE TABLE test1 (a float8, b float8);
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 82
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  SELECT count(*), sum(b), regr_sxx(b,b), sum(b),regr_syy(b,b), regr_sxy(b,b)
	FROM test1;
2022-08-02 08:25:08.733 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.733 UTC [79004] STATEMENT:  SELECT float8_combine('{0,0,0}'::float8[], '{2,180,200}'::float8[]);
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 131
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  explain (verbose, costs off)
	select array(select sum(x+y) s
	            from generate_series(1,3) y group by y order by s)
	  from generate_series(1,3) x;
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  COPY t FROM STDIN NULL 'null';
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  COPY t FROM STDIN NULL 'null';
2022-08-02 08:25:08.734 UTC [79004] WARNING:  SET LOCAL can only be used in transaction blocks
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  set local max_parallel_workers_per_gather = 0;
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  create table bank_account_pkey() inherits (t);
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 19
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  create temp table test1_a_idx(t1 bigint, foo bigint);
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  drop table test1_a_idx, test1;
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  select array_agg(b order by a desc)
	  from (values (1,4),(2,3),(3,1),(4,2)) v(a,b);
2022-08-02 08:25:08.734 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.734 UTC [79004] STATEMENT:  drop view agg_view1;
2022-08-02 08:25:08.735 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-02 08:25:08.735 UTC [79004] STATEMENT:  select string_agg(a,',') from (values('aaaa'),(null),('bbbb'),('cccc')) g(a);
2022-08-02 08:25:08.735 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 14
2022-08-02 08:25:08.735 UTC [79004] STATEMENT:  create table test1(a bytea);
2022-08-02 08:25:08.735 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 106
2022-08-02 08:25:08.735 UTC [79004] STATEMENT:  select percentile_cont(array[0,1,0.25,0.75,0.5,1,0.3,0.32,0.35,0.38,0.4]) within group (order by x)
	from generate_series(1,6) x;
2022-08-02 08:25:08.735 UTC [79004] WARNING:  there is already a transaction in progress
2022-08-02 08:25:08.735 UTC [79004] WARNING:  there is already a transaction in progress
2022-08-02 08:25:08.735 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.735 UTC [79004] STATEMENT:  SET parallel_leader_participation = off;
2022-08-02 08:25:08.735 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.735 UTC [79004] STATEMENT:  SET enable_indexonlyscan = off;
2022-08-02 08:25:08.735 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 8
2022-08-02 08:25:08.735 UTC [79004] STATEMENT:  SELECT min(x ORDER BY y) FROM (VALUES(1, 2)) AS d(x,y);
2022-08-02 08:25:08.735 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.735 UTC [79004] STATEMENT:  set work_mem='64kB';
2022-08-02 08:25:08.735 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.735 UTC [79004] STATEMENT:  set enable_hashagg = true;
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  set jit_above_cost = 0;
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  set enable_sort = true;
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  drop table test1;
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  drop table sqlsim28;
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  drop table sqlsim24;
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  drop table sqlsim2;
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  RESET SESSION AUTHORIZATION;
2022-08-02 08:25:08.736 UTC [79004] WARNING:  there is no transaction in progress
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  DISCARD ALL;
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662 at character 24
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  SELECT n.nspname 
	FROM pg_catalog.pg_namespace n 
	WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema';
2022-08-02 08:25:08.736 UTC [79004] ERROR:  could not find pg_class tuple for index 2662
2022-08-02 08:25:08.736 UTC [79004] STATEMENT:  CREATE SCHEMA public; SET search_path TO public;
2022-08-02 08:25:09.580 UTC [80374] LOG:  logical replication apply worker for subscription "regress_testsub_dummy" has started
2022-08-02 08:25:09.580 UTC [80374] ERROR:  could not connect to the publisher: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
		Is the server running locally and accepting connections on that socket?
2022-08-02 08:25:09.584 UTC [65166] LOG:  background worker "logical replication worker" (PID 80374) exited with exit code 1
2022-08-02 08:25:09.585 UTC [80375] LOG:  logical replication apply worker for subscription "regress_testsub_foo" has started
2022-08-02 08:25:09.586 UTC [80375] ERROR:  could not connect to the publisher: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
		Is the server running locally and accepting connections on that socket?
2022-08-02 08:25:09.590 UTC [65166] LOG:  background worker "logical replication worker" (PID 80375) exited with exit code 1
2022-08-02 08:25:09.950 UTC [80379] PANIC:  could not open critical system index 2662
2022-08-02 08:25:09.952 UTC [65166] LOG:  server process (PID 80379) was terminated by signal 6: Aborted
2022-08-02 08:25:09.952 UTC [65166] LOG:  terminating any other active server processes
2022-08-02 08:25:09.973 UTC [65166] LOG:  all server processes terminated; reinitializing
2022-08-02 08:25:09.994 UTC [80380] LOG:  database system was interrupted; last known up at 2022-08-02 08:24:50 UTC
2022-08-02 08:25:10.024 UTC [80380] LOG:  recovered replication state of node 2 to 0/0
2022-08-02 08:25:10.024 UTC [80380] LOG:  recovered replication state of node 1 to 0/1
2022-08-02 08:25:10.024 UTC [80380] LOG:  recovered replication state of node 6 to 0/0
2022-08-02 08:25:10.024 UTC [80380] LOG:  recovered replication state of node 7 to 0/0
2022-08-02 08:25:10.024 UTC [80380] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-02 08:25:10.025 UTC [80380] LOG:  redo starts at 0/1B72BA28
2022-08-02 08:25:10.045 UTC [80380] LOG:  invalid record length at 0/1B978E38: wanted 24, got 0
